name: Franco28
author: Franco28
version: 1.4
main: me.franco28.Franco28.main
description: Esto es una caja de comandos (para admins), como por ejemplo, "Health" "Kill". ESTABLE.
permission-message: No tienes permisos para usar estos comandos!.

commands:
 kill:
 health:
 food:
 fly:
 cchat:
 citems:
